package com.studieux.bdd;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.studieux.bdd.Devoir;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DEVOIR.
*/
public class DevoirDao extends AbstractDao<Devoir, Long> {

    public static final String TABLENAME = "DEVOIR";

    /**
     * Properties of entity Devoir.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nom = new Property(1, String.class, "nom", false, "NOM");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Deadline = new Property(3, java.util.Date.class, "deadline", false, "DEADLINE");
        public final static Property MatiereId = new Property(4, long.class, "matiereId", false, "MATIERE_ID");
        public final static Property NoteId = new Property(5, Long.class, "noteId", false, "NOTE_ID");
    };

    private DaoSession daoSession;

    private Query<Devoir> matiere_DevoirListQuery;

    public DevoirDao(DaoConfig config) {
        super(config);
    }
    
    public DevoirDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DEVOIR' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOM' TEXT NOT NULL ," + // 1: nom
                "'DESCRIPTION' TEXT," + // 2: description
                "'DEADLINE' INTEGER NOT NULL ," + // 3: deadline
                "'MATIERE_ID' INTEGER NOT NULL ," + // 4: matiereId
                "'NOTE_ID' INTEGER);"); // 5: noteId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DEVOIR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Devoir entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNom());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
        stmt.bindLong(4, entity.getDeadline().getTime());
        stmt.bindLong(5, entity.getMatiereId());
 
        Long noteId = entity.getNoteId();
        if (noteId != null) {
            stmt.bindLong(6, noteId);
        }
    }

    @Override
    protected void attachEntity(Devoir entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Devoir readEntity(Cursor cursor, int offset) {
        Devoir entity = new Devoir( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nom
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            new java.util.Date(cursor.getLong(offset + 3)), // deadline
            cursor.getLong(offset + 4), // matiereId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // noteId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Devoir entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNom(cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeadline(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setMatiereId(cursor.getLong(offset + 4));
        entity.setNoteId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Devoir entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Devoir entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "devoirList" to-many relationship of Matiere. */
    public synchronized List<Devoir> _queryMatiere_DevoirList(long matiereId) {
        if (matiere_DevoirListQuery == null) {
            QueryBuilder<Devoir> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.MatiereId.eq(matiereId));
            matiere_DevoirListQuery = queryBuilder.build();
        } else {
            matiere_DevoirListQuery.setParameter(0, matiereId);
        }
        return matiere_DevoirListQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMatiereDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getNoteDao().getAllColumns());
            builder.append(" FROM DEVOIR T");
            builder.append(" LEFT JOIN MATIERE T0 ON T.'MATIERE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN NOTE T1 ON T.'NOTE_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Devoir loadCurrentDeep(Cursor cursor, boolean lock) {
        Devoir entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Matiere matiere = loadCurrentOther(daoSession.getMatiereDao(), cursor, offset);
         if(matiere != null) {
            entity.setMatiere(matiere);
        }
        offset += daoSession.getMatiereDao().getAllColumns().length;

        Note note = loadCurrentOther(daoSession.getNoteDao(), cursor, offset);
        entity.setNote(note);

        return entity;    
    }

    public Devoir loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Devoir> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Devoir> list = new ArrayList<Devoir>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Devoir> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Devoir> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
