package com.studieux.bdd;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.studieux.bdd.Matiere;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MATIERE.
*/
public class MatiereDao extends AbstractDao<Matiere, Long> {

    public static final String TABLENAME = "MATIERE";

    /**
     * Properties of entity Matiere.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nom = new Property(1, String.class, "nom", false, "NOM");
        public final static Property Moyenne = new Property(2, Float.class, "moyenne", false, "MOYENNE");
        public final static Property Coef = new Property(3, float.class, "coef", false, "COEF");
        public final static Property Cours_ID = new Property(4, Long.class, "cours_ID", false, "COURS__ID");
        public final static Property PeriodeID = new Property(5, long.class, "periodeID", false, "PERIODE_ID");
    };

    private DaoSession daoSession;

    private Query<Matiere> periode_MatiereListQuery;

    public MatiereDao(DaoConfig config) {
        super(config);
    }
    
    public MatiereDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MATIERE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOM' TEXT NOT NULL ," + // 1: nom
                "'MOYENNE' REAL," + // 2: moyenne
                "'COEF' REAL NOT NULL ," + // 3: coef
                "'COURS__ID' INTEGER," + // 4: cours_ID
                "'PERIODE_ID' INTEGER NOT NULL );"); // 5: periodeID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MATIERE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Matiere entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNom());
 
        Float moyenne = entity.getMoyenne();
        if (moyenne != null) {
            stmt.bindDouble(3, moyenne);
        }
        stmt.bindDouble(4, entity.getCoef());
 
        Long cours_ID = entity.getCours_ID();
        if (cours_ID != null) {
            stmt.bindLong(5, cours_ID);
        }
        stmt.bindLong(6, entity.getPeriodeID());
    }

    @Override
    protected void attachEntity(Matiere entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Matiere readEntity(Cursor cursor, int offset) {
        Matiere entity = new Matiere( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nom
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // moyenne
            cursor.getFloat(offset + 3), // coef
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // cours_ID
            cursor.getLong(offset + 5) // periodeID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Matiere entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNom(cursor.getString(offset + 1));
        entity.setMoyenne(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setCoef(cursor.getFloat(offset + 3));
        entity.setCours_ID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setPeriodeID(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Matiere entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Matiere entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "matiereList" to-many relationship of Periode. */
    public synchronized List<Matiere> _queryPeriode_MatiereList(long periodeID) {
        if (periode_MatiereListQuery == null) {
            QueryBuilder<Matiere> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.PeriodeID.eq(periodeID));
            periode_MatiereListQuery = queryBuilder.build();
        } else {
            periode_MatiereListQuery.setParameter(0, periodeID);
        }
        return periode_MatiereListQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPeriodeDao().getAllColumns());
            builder.append(" FROM MATIERE T");
            builder.append(" LEFT JOIN PERIODE T0 ON T.'PERIODE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Matiere loadCurrentDeep(Cursor cursor, boolean lock) {
        Matiere entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Periode periode = loadCurrentOther(daoSession.getPeriodeDao(), cursor, offset);
         if(periode != null) {
            entity.setPeriode(periode);
        }

        return entity;    
    }

    public Matiere loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Matiere> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Matiere> list = new ArrayList<Matiere>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Matiere> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Matiere> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
